apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: ashapp
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""   # must match PVC
  hostPath:
    path: /mnt/data/mysql
  claimRef:                # Bind directly to StatefulSet-generated PVC
    namespace: ashapp
    name: mysql-storage-mysql-0
